id: P901CF678
initial_creation_type: ocr
source_metadata:
  volumes:
    0133d2d98b0d45999e415010cf9d3714:
      base_file: v070.txt
      image_group_id: I1PD95915
      title: མདོ་སྡེའི་རྒྱན་གྱི་བཤད་པ།
      total_pages: 1505
      volume_number: 70
